/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Account {
    'id'?: number;
    'uuid'?: string;
    'name'?: string;
    'username'?: string;
    'image'?: string;
    'provider'?: Account.ProviderEnum;
    /**
    * Provider-specific metadata.
    */
    'data'?: object;
    'authorized'?: boolean;
    'createdAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "Account.ProviderEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "authorized",
            "baseName": "authorized",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }
}

export namespace Account {
    export enum ProviderEnum {
        Instagram = <any> 'instagram',
        Tiktok = <any> 'tiktok',
        Pinterest = <any> 'pinterest',
        Twitter = <any> 'twitter',
        Linkedin = <any> 'linkedin',
        FacebookPage = <any> 'facebook_page',
        Youtube = <any> 'youtube',
        Mastodon = <any> 'mastodon'
    }
}
