/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* At least one of `url` or (`title` + `excerpt`) must be provided. If both are given, direct values take priority over the scraped URL content. 
*/
export class BlogToSocialInput {
    /**
    * Blog post URL to scrape. Required if `title` and `excerpt` are not provided.
    */
    'url'?: string;
    /**
    * Blog post title. Required if `url` is not provided.
    */
    'title'?: string;
    /**
    * Blog post summary or excerpt. Required if `url` is not provided.
    */
    'excerpt'?: string;
    /**
    * Featured image URL for the blog post. When `create_post` is `true`, the image is imported into the workspace media library and attached to the draft post. If omitted in URL mode, the scraper attempts to extract the `og:image` meta tag. 
    */
    'imageUrl'?: string;
    /**
    * Target social media platforms. Only connected accounts matching these platforms are used. If omitted, all connected accounts in the workspace are targeted. 
    */
    'platforms'?: Array<BlogToSocialInput.PlatformsEnum>;
    /**
    * Specific account IDs to generate captions for. Takes precedence over `platforms` when both are provided. 
    */
    'accountIds'?: Array<number>;
    /**
    * Writing tone for all generated captions.
    */
    'tone'?: BlogToSocialInput.ToneEnum = BlogToSocialInput.ToneEnum.Engaging;
    /**
    * Desired length of the generated captions.
    */
    'contentLength'?: BlogToSocialInput.ContentLengthEnum = BlogToSocialInput.ContentLengthEnum.Medium;
    /**
    * Hashtag quantity: none (0), few (1-3), some (3-5), many (5+).
    */
    'hashtags'?: BlogToSocialInput.HashtagsEnum = BlogToSocialInput.HashtagsEnum.Few;
    /**
    * Call-to-action type appended to each caption.
    */
    'cta'?: BlogToSocialInput.CtaEnum = BlogToSocialInput.CtaEnum.None;
    /**
    * Output language as an ISO 639-1 code (e.g. `en`, `de`, `fr`). Use `auto` to match the blog post\'s language automatically. 
    */
    'language'?: string = 'auto';
    /**
    * Additional instructions appended to the AI prompt (e.g. \"always mention our free tier\").
    */
    'customInstructions'?: string;
    /**
    * When `true`, creates a draft post in the workspace with per-account caption versions. If an image is available, it is imported and attached to the post. 
    */
    'createPost'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "excerpt",
            "baseName": "excerpt",
            "type": "string"
        },
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string"
        },
        {
            "name": "platforms",
            "baseName": "platforms",
            "type": "Array<BlogToSocialInput.PlatformsEnum>"
        },
        {
            "name": "accountIds",
            "baseName": "account_ids",
            "type": "Array<number>"
        },
        {
            "name": "tone",
            "baseName": "tone",
            "type": "BlogToSocialInput.ToneEnum"
        },
        {
            "name": "contentLength",
            "baseName": "content_length",
            "type": "BlogToSocialInput.ContentLengthEnum"
        },
        {
            "name": "hashtags",
            "baseName": "hashtags",
            "type": "BlogToSocialInput.HashtagsEnum"
        },
        {
            "name": "cta",
            "baseName": "cta",
            "type": "BlogToSocialInput.CtaEnum"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "customInstructions",
            "baseName": "custom_instructions",
            "type": "string"
        },
        {
            "name": "createPost",
            "baseName": "create_post",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BlogToSocialInput.attributeTypeMap;
    }
}

export namespace BlogToSocialInput {
    export enum PlatformsEnum {
        Facebook = <any> 'facebook',
        Instagram = <any> 'instagram',
        X = <any> 'x',
        Linkedin = <any> 'linkedin',
        Pinterest = <any> 'pinterest',
        Youtube = <any> 'youtube',
        Tiktok = <any> 'tiktok',
        Mastodon = <any> 'mastodon',
        Threads = <any> 'threads',
        Bluesky = <any> 'bluesky',
        GoogleBusiness = <any> 'google_business'
    }
    export enum ToneEnum {
        Neutral = <any> 'neutral',
        Friendly = <any> 'friendly',
        Formal = <any> 'formal',
        Edgy = <any> 'edgy',
        Engaging = <any> 'engaging',
        Casual = <any> 'casual',
        Professional = <any> 'professional',
        Humorous = <any> 'humorous',
        Inspirational = <any> 'inspirational',
        Conversational = <any> 'conversational'
    }
    export enum ContentLengthEnum {
        Short = <any> 'short',
        Medium = <any> 'medium',
        Long = <any> 'long'
    }
    export enum HashtagsEnum {
        None = <any> 'none',
        Few = <any> 'few',
        Some = <any> 'some',
        Many = <any> 'many'
    }
    export enum CtaEnum {
        None = <any> 'none',
        Question = <any> 'question',
        Link = <any> 'link',
        Subscribe = <any> 'subscribe',
        Follow = <any> 'follow',
        Share = <any> 'share',
        LearnMore = <any> 'learn_more',
        Signup = <any> 'signup',
        Buy = <any> 'buy',
        Download = <any> 'download'
    }
}
