/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlogToSocialCaption } from './blogToSocialCaption';
import { BlogToSocialMedia } from './blogToSocialMedia';

export class BlogToSocialResponse {
    /**
    * The blog post title (scraped or provided directly).
    */
    'blogTitle'?: string;
    /**
    * A short excerpt from the blog post content.
    */
    'blogExcerpt'?: string;
    /**
    * Generated captions, one per target account.
    */
    'captions'?: Array<BlogToSocialCaption>;
    /**
    * UUID of the created draft post. Only present when `create_post` was `true`.
    */
    'postUuid'?: string;
    'media'?: BlogToSocialMedia;
    /**
    * Number of AI credits consumed by this request (one per successful caption).
    */
    'creditsUsed'?: number;
    /**
    * Remaining AI credits for the current billing period. `null` for unlimited plans.
    */
    'creditsRemaining'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blogTitle",
            "baseName": "blog_title",
            "type": "string"
        },
        {
            "name": "blogExcerpt",
            "baseName": "blog_excerpt",
            "type": "string"
        },
        {
            "name": "captions",
            "baseName": "captions",
            "type": "Array<BlogToSocialCaption>"
        },
        {
            "name": "postUuid",
            "baseName": "post_uuid",
            "type": "string"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "BlogToSocialMedia"
        },
        {
            "name": "creditsUsed",
            "baseName": "credits_used",
            "type": "number"
        },
        {
            "name": "creditsRemaining",
            "baseName": "credits_remaining",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BlogToSocialResponse.attributeTypeMap;
    }
}

