/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BlogToSocialCaption {
    /**
    * ID of the social account this caption was generated for.
    */
    'accountId'?: number;
    /**
    * Social media platform identifier.
    */
    'provider'?: string;
    /**
    * The generated caption text. `null` if generation failed for this account.
    */
    'content'?: string;
    /**
    * Character count of the generated content. `null` if generation failed.
    */
    'characterCount'?: number;
    /**
    * Maximum allowed character count for this platform.
    */
    'characterLimit'?: number;
    /**
    * Error message if caption generation failed for this account. `null` on success.
    */
    'error'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "number"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "characterCount",
            "baseName": "character_count",
            "type": "number"
        },
        {
            "name": "characterLimit",
            "baseName": "character_limit",
            "type": "number"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BlogToSocialCaption.attributeTypeMap;
    }
}

