/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ImagePromptInput {
    'caption': string;
    'platform': string;
    'template'?: ImagePromptInput.TemplateEnum;
    'style'?: string;
    'brandVoice'?: string;
    'customInstructions'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "ImagePromptInput.TemplateEnum"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "string"
        },
        {
            "name": "brandVoice",
            "baseName": "brand_voice",
            "type": "string"
        },
        {
            "name": "customInstructions",
            "baseName": "custom_instructions",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ImagePromptInput.attributeTypeMap;
    }
}

export namespace ImagePromptInput {
    export enum TemplateEnum {
        BlogCover = <any> 'blog_cover',
        QuoteCard = <any> 'quote_card',
        StatCard = <any> 'stat_card',
        FeatureAnnouncement = <any> 'feature_announcement',
        ProductHighlight = <any> 'product_highlight',
        EventPromo = <any> 'event_promo',
        CarouselSlide = <any> 'carousel_slide',
        AdCreative = <any> 'ad_creative'
    }
}
