/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ImageGenerateInput {
    /**
    * Social media caption. Triggers standard mode. Takes priority over prompt.
    */
    'caption'?: string;
    /**
    * Required when caption is provided.
    */
    'platform'?: string;
    'template'?: ImageGenerateInput.TemplateEnum;
    'style'?: string;
    'brandVoice'?: string;
    'customInstructions'?: string;
    /**
    * Developer escape hatch. Bypasses internal prompt builder. Ignored if caption is present.
    */
    'prompt'?: string;
    'aspectRatio'?: ImageGenerateInput.AspectRatioEnum = ImageGenerateInput.AspectRatioEnum._11;
    'count'?: number = 1;
    'quality'?: ImageGenerateInput.QualityEnum = ImageGenerateInput.QualityEnum.Standard;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "ImageGenerateInput.TemplateEnum"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "string"
        },
        {
            "name": "brandVoice",
            "baseName": "brand_voice",
            "type": "string"
        },
        {
            "name": "customInstructions",
            "baseName": "custom_instructions",
            "type": "string"
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string"
        },
        {
            "name": "aspectRatio",
            "baseName": "aspect_ratio",
            "type": "ImageGenerateInput.AspectRatioEnum"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "quality",
            "baseName": "quality",
            "type": "ImageGenerateInput.QualityEnum"
        }    ];

    static getAttributeTypeMap() {
        return ImageGenerateInput.attributeTypeMap;
    }
}

export namespace ImageGenerateInput {
    export enum TemplateEnum {
        BlogCover = <any> 'blog_cover',
        QuoteCard = <any> 'quote_card',
        StatCard = <any> 'stat_card',
        FeatureAnnouncement = <any> 'feature_announcement',
        ProductHighlight = <any> 'product_highlight',
        EventPromo = <any> 'event_promo',
        CarouselSlide = <any> 'carousel_slide',
        AdCreative = <any> 'ad_creative'
    }
    export enum AspectRatioEnum {
        _11 = <any> '1:1',
        _169 = <any> '16:9',
        _916 = <any> '9:16',
        _45 = <any> '4:5'
    }
    export enum QualityEnum {
        Standard = <any> 'standard',
        Hd = <any> 'hd'
    }
}
