/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ImageVariationsInput {
    'mediaUuid': string;
    'aspectRatio'?: ImageVariationsInput.AspectRatioEnum = ImageVariationsInput.AspectRatioEnum._11;
    'count'?: number = 1;
    'quality'?: ImageVariationsInput.QualityEnum = ImageVariationsInput.QualityEnum.Standard;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mediaUuid",
            "baseName": "media_uuid",
            "type": "string"
        },
        {
            "name": "aspectRatio",
            "baseName": "aspect_ratio",
            "type": "ImageVariationsInput.AspectRatioEnum"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "quality",
            "baseName": "quality",
            "type": "ImageVariationsInput.QualityEnum"
        }    ];

    static getAttributeTypeMap() {
        return ImageVariationsInput.attributeTypeMap;
    }
}

export namespace ImageVariationsInput {
    export enum AspectRatioEnum {
        _11 = <any> '1:1',
        _169 = <any> '16:9',
        _916 = <any> '9:16',
        _45 = <any> '4:5'
    }
    export enum QualityEnum {
        Standard = <any> 'standard',
        Hd = <any> 'hd'
    }
}
