/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InitiateRemoteUpload200ResponseOneOf } from './initiateRemoteUpload200ResponseOneOf';
import { Media } from './media';

export class InitiateRemoteUpload200Response {
    'id'?: number;
    'uuid'?: string;
    'name'?: string;
    'mimeType'?: string;
    'type'?: InitiateRemoteUpload200Response.TypeEnum;
    'url'?: string;
    'thumbUrl'?: string;
    'isVideo'?: boolean;
    'createdAt'?: Date;
    'downloadId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "mimeType",
            "baseName": "mime_type",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "InitiateRemoteUpload200Response.TypeEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "thumbUrl",
            "baseName": "thumb_url",
            "type": "string"
        },
        {
            "name": "isVideo",
            "baseName": "is_video",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "downloadId",
            "baseName": "download_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InitiateRemoteUpload200Response.attributeTypeMap;
    }
}

export namespace InitiateRemoteUpload200Response {
    export enum TypeEnum {
        Image = <any> 'image',
        Video = <any> 'video',
        Gif = <any> 'gif'
    }
}
