/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaginationMetaLinks } from './paginationMetaLinks';
import { PaginationMetaMeta } from './paginationMetaMeta';
import { Workspace } from './workspace';

export class ListWorkspaces200Response {
    'links'?: PaginationMetaLinks;
    'meta'?: PaginationMetaMeta;
    'data'?: Array<Workspace>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "links",
            "type": "PaginationMetaLinks"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PaginationMetaMeta"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Workspace>"
        }    ];

    static getAttributeTypeMap() {
        return ListWorkspaces200Response.attributeTypeMap;
    }
}

