/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostContent } from './postContent';

export class PostVersion {
    /**
    * Use `0` for the original/default version.
    */
    'accountId': number;
    /**
    * Must be `true` for the first version.
    */
    'isOriginal': boolean;
    'content': Array<PostContent>;
    /**
    * Platform-specific publishing options.
    */
    'options'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "number"
        },
        {
            "name": "isOriginal",
            "baseName": "is_original",
            "type": "boolean"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "Array<PostContent>"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return PostVersion.attributeTypeMap;
    }
}

