/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostVersion } from './postVersion';

export class PostInput {
    /**
    * At least one version with `is_original: true` is required.
    */
    'versions': Array<PostVersion>;
    /**
    * Account IDs to publish to.
    */
    'accounts'?: Array<number>;
    /**
    * Tag IDs to attach.
    */
    'tags'?: Array<number>;
    'date'?: string;
    'time'?: string;
    'timezone'?: string;
    /**
    * Schedule the post for the given date/time.
    */
    'schedule'?: boolean;
    /**
    * Publish immediately.
    */
    'scheduleNow'?: boolean;
    /**
    * Add to the smart publishing queue.
    */
    'queue'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<PostVersion>"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<number>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<number>"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "boolean"
        },
        {
            "name": "scheduleNow",
            "baseName": "schedule_now",
            "type": "boolean"
        },
        {
            "name": "queue",
            "baseName": "queue",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PostInput.attributeTypeMap;
    }
}

