/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostContent {
    /**
    * Post text/caption.
    */
    'body'?: string;
    'url'?: string;
    /**
    * Array of media IDs from the media library.
    */
    'media'?: Array<number>;
    'videoThumbs'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "Array<number>"
        },
        {
            "name": "videoThumbs",
            "baseName": "video_thumbs",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return PostContent.attributeTypeMap;
    }
}

