/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionStatus } from './subscriptionStatus';

export class SubscriptionUpdateInput {
    'platformPlanId': string;
    'status': SubscriptionStatus;
    /**
    * Required when status is `trialing`.
    */
    'trialEndsAt'?: Date;
    /**
    * Required when status is `paused`.
    */
    'pausedFrom'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "platformPlanId",
            "baseName": "platform_plan_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SubscriptionStatus"
        },
        {
            "name": "trialEndsAt",
            "baseName": "trial_ends_at",
            "type": "Date"
        },
        {
            "name": "pausedFrom",
            "baseName": "paused_from",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionUpdateInput.attributeTypeMap;
    }
}

export namespace SubscriptionUpdateInput {
}
