/**
 * PostBoost API
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { User } from './user';

export class Workspace {
    'uuid'?: string;
    'name'?: string;
    'hexColor'?: string;
    'owner'?: User;
    'accessStatus'?: Workspace.AccessStatusEnum;
    'createdAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "hexColor",
            "baseName": "hex_color",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "User"
        },
        {
            "name": "accessStatus",
            "baseName": "access_status",
            "type": "Workspace.AccessStatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Workspace.attributeTypeMap;
    }
}

export namespace Workspace {
    export enum AccessStatusEnum {
        Subscription = <any> 'subscription',
        Unlimited = <any> 'unlimited',
        Locked = <any> 'locked'
    }
}
